name: Linter

on: push

jobs:
  lint:
    name: Lint code base
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: Run linter
        uses: github-super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: $({ secrets.GITHUB_TOKEN })
      
